spring.application.name=loan-rate-matcher-v2

spring.datasource.url=jdbc:postgresql://localhost:5432/loanmatcher
spring.datasource.username=loanmatcher
spring.datasource.password=loanmatcher

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
